# Generated by Django 3.0.6 on 2020-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('not specified', 'not specified')], max_length=13)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
