# Generated by Django 3.0.6 on 2020-05-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/'),
        ),
    ]
